parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            breed: Elewant\Webapp\Infrastructure\Doctrine\BreedMappingType
            shepherd_id: Elewant\Webapp\Infrastructure\Doctrine\ShepherdIdMappingType
        schema_filter: "/^(?!event_stream).*$/"
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Elewant\Webapp\DomainModel\Herding:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Elewant/Webapp/DomainModel/Herding/'
                prefix: 'Elewant\Webapp\DomainModel\Herding'
                alias: Herding
