hwi_oauth:
    firewall_names: [herd_management]
    resource_owners:
        twitter:
            type:          twitter
            client_id:     "%twitter_client_id%"
            client_secret: "%twitter_client_secret%"
    connect:
        confirmation:              true
        registration_form:         security.registration.form
        registration_form_handler: security.registration.form_handler
        account_connector:         security.account.connector

services:
    security.registration.form:
        class: Bundles\UserBundle\Form\UserType
        factory: ["@form.factory","create"]
        arguments:
            - 'Bundles\UserBundle\Form\UserType'

    security.registration.form_handler:
        class: Bundles\UserBundle\Form\RegistrationFormHandler
        arguments:
            - '@security.user_provider'

    security.account.connector: '@security.user_provider'

    security.user_provider:
        class: Bundles\UserBundle\Security\UserProvider
        public: true
        arguments:
            - '@doctrine'
            - '@event_dispatcher'
