language: php
php:
  - '7.4'

env:
  - TEST_SUITE="main"

branches:
  only:
    - master
    - develop

addons:
  hosts:
    - elewant.loc
    - database-test
  mariadb: "10.2"

cache:
  directories:
    - vendor

install:
  - cp tests/config/.env_for_travis .env
  - mysql -e "create database elewant_test;"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'elewant'@'%' IDENTIFIED BY 'elewant'"
  - make composer-install

before_script:
  - echo 'date.timezone = "Europe/Amsterdam"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini

script:
  - SYMFONY_DEPRECATIONS_HELPER=disabled make ci

notifications:
  email:
    on_success: change
