---

# GENERAL

ssh_provision_user: "vagrant"
bashrc_users:
  - "vagrant"

# UFW

ufw_rules_to_create:
  - direction: in
    to_port: 22
    rule: allow
  - direction: in
    to_port: 80
    rule: allow
  - direction: in
    to_port: 3306
    rule: allow

# MariaDB

mariadb_bind_address: 192.168.77.77

mariadb_root_password: elewant
mariadb_passwords:
  elewant_develop: elewant

mariadb_databases:
  - elewant
  - elewant_test

mariadb_users:
  - { name: elewant, password: "{{ mariadb_passwords.elewant_develop }}", priv: "elewant.*:ALL/elewant_test.*:ALL", host: "%" }

mariadb_slow_query_log_enabled: true
mariadb_long_query_time: 2

# PHP

php7_extensions: [ apcu, xdebug ]
php7_versioned_extensions: [ curl, intl, mbstring, mysql, sqlite3, zip, xml ]

php7_fpm_pool_user: vagrant
php7_fpm_pool_group: vagrant

php7_ini_directives_global:
  disable_functions: "exec, system, popen, curl_multi_exec"
  session.cookie_secure: off
  opcache.enable_cli: on
  opcache.fast_shutdown: off
  opcache.interned_strings_buffer: 16
  opcache.max_accelerated_files: 20480
  opcache.memory_consumption: 128
  opcache.revalidate_freq: off
  opcache.validate_timestamps: on
  xdebug.cli_color: yes
  xdebug.collect_params: 3
  xdebug.idekey: PHPSTORM
  xdebug.remote_enable: yes
  xdebug.remote_host: 192.168.77.1
  xdebug.remote_port: 9000
  xdebug.var_display_max_depth: 4

php7_ini_directives_fpm:
  xdebug.remote_autostart: on

# NGINX

nginx_user: "{{ php7_fpm_pool_user }}"
nginx_group: "{{ php7_fpm_pool_group }}"
nginx_dhparam_bits: 128
nginx_use_realpath_root: yes

nginx_http_headers:
  Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://*.githubusercontent.com; form-action 'self'; frame-ancestors 'none'"

nginx_server_templates:
  - name: elewant
    src: "{{ playbook_dir }}/templates/nginx/dev-server.conf.j2"
    domains:
      - "develop.elewant.loc"
    web_root: "/vagrant/public"
    index: index.php
    headers: "{{ nginx_http_headers }}"

# APP

elewant_application_root: /vagrant
elewant_application_env: dev

elewant_db_name: elewant
elewant_db_user: elewant
elewant_db_password: "{{ mariadb_passwords.elewant_develop }}"
elewant_delivery_address: "~"
elewant_secret: SaG125fH0Alz8NIMIQdYGQEizoeZJVlQlbpFIDgEhQeyOalfPBkvowShgFkaruVu
elewant_twitter_client: "needs_client_id"
elewant_twitter_secret: "needs_client_secret"
elewant_tweets_are_active: false
elewant_tweets_app_consumerkey: "~"
elewant_tweets_app_consumersecret: "~"
elewant_tweets_app_accesstoken: "~"
elewant_tweets_app_accesstokensecret: "~"
