# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

parameters:

    locale: 'en'

    github_username: f500
    github_repository: elewant
    github_contributor_blacklist: ['waffle-iron']

    twitter_client_id: '%env(TWITTER_CLIENT_ID)%'
    twitter_client_secret: '%env(TWITTER_CLIENT_SECRET)%'

    elewant_tweets_are_active: '%env(bool:ELEWANT_TWEETS_ARE_ACTIVE)%'
    elewant_tweets_app_consumerkey: '%env(ELEWANT_TWEETS_APP_CONSUMERKEY)%'
    elewant_tweets_app_consumersecret: '%env(ELEWANT_TWEETS_APP_CONSUMERSECRET)%'
    elewant_tweets_app_accesstoken: '%env(ELEWANT_TWEETS_APP_ACCESSTOKEN)%'
    elewant_tweets_app_accesstokensecret: '%env(ELEWANT_TWEETS_APP_ACCESSTOKENSECRET)%'

services:

    # default configuration for services in *this* file
    _defaults:

        # Automatically injects dependencies in your services.
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.
        public: false

    # HERDING

    Elewant\Herding\Infrastructure\:
        resource: '../src/Elewant/Herding/Infrastructure/'

    Elewant\Herding\Application\:
        resource: '../src/Elewant/Herding/Application/'

    Elewant\Herding\Application\Commands\:
        resource: '../src/Elewant/Herding/Application/Commands/'
        arguments:
            - '@herd_collection'
        tags:
            - { name: 'prooph_service_bus.herding_command_bus.route_target', message_detection: true }

    # REPORTING

    Elewant\Reporting\Infrastructure\:
        resource: '../src/Elewant/Reporting/Infrastructure/'

    Elewant\Reporting\Infrastructure\SymfonyConsole\:
        resource: '../src/Elewant/Reporting/Infrastructure/SymfonyConsole/'
        tags:
            - 'console.command'

    Elewant\Reporting\Application\:
        resource: '../src/Elewant/Reporting/Application/'

    Elewant\Reporting\Application\EventSubscribers\NotifyTwitter:
        arguments:
            - '@Abraham\TwitterOAuth\TwitterOAuth'
            - '%elewant_tweets_are_active%'

    Elewant\Reporting\DomainModel\HerdingStatisticsCalculator:
        alias: 'Elewant\Reporting\Infrastructure\Doctrine\DoctrineHerdingStatisticsCalculator'

    # WEBAPP

    Elewant\Webapp\Infrastructure\:
        resource: '../src/Elewant/Webapp/Infrastructure/'

    Elewant\Webapp\Infrastructure\Github\GithubContributorList:
        arguments:
            - '%github_username%'
            - '%github_repository%'
            - "@httplug.message_factory"
            - "@httplug.client"
            - '%github_contributor_blacklist%'

    Elewant\Webapp\Infrastructure\ProophProjections\HerdListing:
        public: true

    Elewant\Webapp\Application\:
        resource: '../src/Elewant/Webapp/Application/'
        exclude: '../src/Elewant/Webapp/Application/{Resources}'

    Elewant\Webapp\Application\Controllers\:
        resource: '../src/Elewant/Webapp/Application/Controllers/'
        tags:
            - 'controller.service_arguments'

    Elewant\Webapp\DomainModel\Contributor\ContributorList:
        alias: 'Elewant\Webapp\Infrastructure\Github\GithubContributorList'

    Elewant\Webapp\DomainModel\Herding\HerdRepository:
        alias: 'Elewant\Webapp\Infrastructure\Doctrine\DoctrineHerdRepository'

    # REPORTING
    Elewant\Reporting\DomainModel\Statistics\NumberOf:
        alias: 'Elewant\Reporting\Infrastructure\Doctrine\Statistics\NumberOfRepository'

    # BUNDLES

    Abraham\TwitterOAuth\TwitterOAuth:
        arguments:
            - "%elewant_tweets_app_consumerkey%"
            - "%elewant_tweets_app_consumersecret%"
            - "%elewant_tweets_app_accesstoken%"
            - "%elewant_tweets_app_accesstokensecret%"

    Bundles\DevelopmentBundle\:
        resource: '../src/Bundles/DevelopmentBundle/'
        exclude: '../src/Bundles/DevelopmentBundle/{Resources,DevelopmentBundle.php}'

    Bundles\DevelopmentBundle\Controller\:
        resource: '../src/Bundles/DevelopmentBundle/Controller/'
        tags:
            - 'controller.service_arguments'

    Bundles\UserBundle\:
        resource: '../src/Bundles/UserBundle/'
        exclude: '../src/Bundles/UserBundle/{Entity,Event,Resources,UserBundle.php}'

    # TOOLING

    Tooling\SymfonyConsole\:
        resource: '../src/Tooling/SymfonyConsole/'
        arguments:
            $eventStore: '@prooph_event_store.herd_store'
        tags:
            - 'console.command'

    monolog.formatter.json-with-exceptions:
        class: Monolog\Formatter\JsonFormatter
        calls:
            - { method: includeStacktraces }
