name: Deploy to production

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy to elewant.com on tag
        uses: ./.github/actions/ansible
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
        with:
          extraVars: "--limit=production --extra project_version=${{ github.sha }}"
          verbosity: ""
